targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/repositories/graphql/graphql_api.dart
              schema: lib/repositories/graphql/schema.graphql
              queries_glob: lib/repositories/graphql/queries/**.graphql
          fragments_glob: lib/repositories/graphql/fragments/**.graphql
